steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/crucial-bloom-441721-v1/group-repo/app:$SHORT_SHA'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/crucial-bloom-441721-v1/group-repo/app:$SHORT_SHA'

  # Step 3: Deploy the Docker container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'app-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/crucial-bloom-441721-v1/group-repo/app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
    env:
      - 'CLOUDSDK_CORE_PROJECT=crucial-bloom-441721-v1'

options:
  logging: CLOUD_LOGGING_ONLY  # Logs only in Cloud Logging

images:
  - 'us-central1-docker.pkg.dev/crucial-bloom-441721-v1/group-repo/app@sha256:88a47b5341db0bbc72049e3bd0c2c7f52436f7da282ec8fb279686c1cf4c80b9'
